### ISSUE TITLE
Generating GPX file for Darktable

### ISSUE THREAD

**Issue by jcubic** [BradPatras/gpx-recorder#22]
I want to generate GPX file for darktable open source program that will add GPS coordinates to my photos. I've installed the app to test it. Is there a way to test while staying at home? or do I need to go somewhere to test it? Because it show 0 waypoint, shouldn't show at least first staring point?

**Comment by BradPatras** [comment]
You can test it with a location mocking app (lots of them on the Google Play Store) 

Currently the app requests location updates from the system based on movement, so the location will not update unless you are moving (generally).

It may be a good idea to add a starting point at the beginning.

**Comment by BradPatras** [comment]
Enhancement that will address this issue #23
