### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [BradPatras/gpx-recorder#36]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Could you please in the meantime tag your [releases](https://github.com/BradPatras/gpx-recorder/releases) and attach a signed release apk to it, so that people without Play Store can download it. Thanks.

**Comment by BradPatras** [comment]
I would love to but i'm a little fuzzy on how to handle secret api keys in the case of f-droid.  Currently an api key necessary for the app to function (google maps api key) is omitted from the source code and is only accessible by me. Uploading the signed apk would open it up for easy access to the secret key via decompilation.  
How do other f-droid apps keep their secret keys secret?

**Comment by Poussinou** [comment]
@izzysoft has a better knowledge than me on this.

**Comment by Poussinou** [comment]
F-Droid cannot store keys itself, so it'll have to be in the source code one way or another.

People can still get your keys from the APK hosted on Google Play actually.

I just had a look at your build.gradle file, F-Droid cannot build this app due to non FLOSS dependencies (you would have to switch to OpenStreetMap and remove other proprietary stuff) and it's a lot of work.

Could you please then attached a signed release APK to your Releases Section for people without GooglePlay?

**Comment by BradPatras** [comment]
Not interested in converting to OpenStreetMap at this time, but I have included a signed apk in the most recent release.
