### ISSUE TITLE
Czech language translation

### ISSUE THREAD

**Issue by pocitas** [BradPatras/gpx-recorder#42]
Hello,

I recommended your application to the friend of mine, as a perfect fit for his needs (hiking, biking).
Unfortunately, he doesn't understand english at all.

I made a czech strings.xml version: [http://pocitas.cz/values-cs.zip](http://pocitas.cz/values-cs.zip)
It would be nice, if you could include it in the next release.

I have translated even strings, marked as `translatable="false"`, because I consider it important. So please remove the "untranslatable" attribute from the default (english) strings.xml file.
If you use the Translations Editor Tool of Android Studio, after you add the "cs" language, these keys are marked red as an error and can be simply fixed by unchecking the "untranslatable" checkbox.

Thanks for the very good application.

Martin

**Comment by BradPatras** [comment]
@pocitas Thanks so much for those translations, i've added them but I found a few more strings that need translated, If i could get you to translate these last strings then i'll get the update released!
- Export File
- File format
- Recorded routes will show up here
- Start recording button
- Route Deleted
- Tap to Undo

**Comment by pocitas** [comment]
Export File
**Exportovat Soubor**

File format
**Formát souboru**

Recorded routes will show up here
**Zde budou zobrazeny zaznamenané cesty**

Start recording button
**Tlačítko spuštění záznamu**

Route Deleted
**Cesta Odstraněna**

Tap to Undo
**Klepnutím Vrátit Zpět**


I see you've added some new strings yourself.
h/m/s is OK.
The word _email_ in this form "_E-mailem_" , means "by email". Like in a "Send by email." = "Poslat e-mailem".
I don't see a context because I am out today. But if the meaning should be the label for an email address, like "Email: xxx@yyy.zz", then you should use "**E-mail**". The dash is not mandatory. Sometimes we use it, sometimes not. No rule.

Thank you. You are incredibly fast.
