### ISSUE TITLE
Wrong timestamp in GPX export file

### ISSUE THREAD

**Issue by larskarla** [BradPatras/gpx-recorder#47]
Did a recording on an airplane last week, with an interval of 30 s between points.
The gpx export file has wierd timestamps.
The first timestamp is just for one single position, the next is 9:15 minutes later and repeated for 7 positions, next is 8:48 later and repeated for 16 positions, next is one second later and repeated for 5, and so on.
Total of 300 points for a 2.5 hour trip so that adds up, but the timestamps are all wrong.
A graph of the elevation points gives a smooth curve so the position intervals is correct.

First points:
<trkseg><trkpt lat="64.623818" lon="21.0679148"><ele>68,000</ele> <time>2023-12-18T05:05:50Z</time></trkpt><trkpt lat="64.6237439" lon="21.0679483"><ele>65,336</ele> <time>2023-12-18T05:15:05Z</time></trkpt><trkpt lat="64.6239185" lon="21.0686866"><ele>66,277</ele> <time>2023-12-18T05:15:05Z</time></trkpt><trkpt lat="64.6237554" lon="21.0681295"><ele>63,706</ele> <time>2023-12-18T05:15:05Z</time></trkpt><trkpt lat="64.623716" lon="21.0679236"><ele>63,706</ele> <time>2023-12-18T05:15:05Z</time></trkpt>....

**Comment by BradPatras** [comment]
I think you've uncovered a really silly bug in the code, I'm assuming that getting a GPS fix in an airplane is really tough so the system is sending a bunch of location updates in batches. (like in your example, 7 at once, 16 at once, etc.)  The app receives these updates all in one batch and applies the current time to all of them.  The app should be offsetting the timestamp by the age attached to each individual location object.

Thanks for opening this issue! I will work on getting a fix out soon.
